apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamparser
  labels:
    app: sp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sp
    template:
      metadata:
        labels:
          app: sp
      spec:
        conatiners:
          - name: sp
            image: dlstream/stream-parser:v01
            ports:
              - containerPort: 80