apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-01
  namespace: dlstream
spec:
  selector:
    matchLabels:
      app: sp-01
  replicas: 1
  template:
    metadata:
      labels:
        app: sp-01
    spec:
      containers:
      - name: sp-01
        image: yejyang/stream-parser:v01
        env:
        - name: LOOP_BACK_WIN_SIZE
          value: "3"
        - name: INPUT_SHIFT_STEP
          value: "1"
        - name: SRC
          value: "0"
        - name: DST
          value: "cep0"
        - name: LOOK_FORWARD_STEP
          value: "1"
        - name: LOOK_FORWARD_WIN_SIZE
          value: "1"
        - name: IS_ONLINE_TRAIN
          value: "True"
        - name: BOOTSTRAP_SERVERS
          value: "{KAFKA_IP}"
