apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelrepo
  labels:
    app: modelrepo
  namespace: dlstream
spec:
  selector:
    matchLabels:
      app: modelrepo
  replicas: 1
  template:
    metadata:
      labels:
        app: modelrepo
    spec:
      containers:
        - name: modelrepo
          image: yejyang/model-repo:v01
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: modelrepo
  labels:
    app: modelrepo
  namespace: dlstream
spec:
  ports:
    - port: 8888
  selector:
    app: modelrepo
